### ISSUE TITLE
Get bus error when running

### ISSUE THREAD

**Issue by pmpbar** [mmcdan/visualpru#1]
Hello,
I think I have everything set up, however, when I actually access the page from my computer I get:
'pid' bus error  python visualpru.py
from the beaglebone. Not really sure what the deal is. I'm going to investigate.

**Comment by mmcdan** [comment]
@pmpbar sounds like you might not have the PRU hardware enabled. Try typing `cat /sys/devices/bone_capemgr.*/slots` and make sure that you have an overlay loaded which enables the PRU hardware. I highly recommend that you use the [universal overlay](https://github.com/cdsteinkuehler/beaglebone-universal-io), since it makes life much easier. Alternative is to take a look in /lib/firmware and export your PRU overlay.

**Comment by pmpbar** [comment]
Thanks.
